### PR TITLE
Document custom workflow usage

### PR DESCRIPTION
**Pull request by j-f1**

### CODE REVIEW

**Comment by gebeto** [comment]
Unfortunately this will not work because deployemnt only available from `gh-pages` branch
Screenshot 2022-05-15 at 10 36 47

**Comment by j-f1** [comment]
Oh right, I forgot about that! You'll need to go to repository settings → Environments → GitHub Pages, change “Deployment branches” to “Selected branches” and then not select any branches. I’ll update the README with this workaround.

image

**Comment by gebeto** [comment]
There can be also selected `main` branch for github pages(it will just enable pages), then you can disable pages deploy workflow in actions and everything will work too without extra `gh-pages` branch

Screenshot 2022-05-15 at 16 56 44

**Comment by yoannchaudet** [comment]
@j-f1 Thank you for your contribution!

We are not merging this on purpose at the moment in light of some changes we are doing now in the background and should be ready to share within a few weeks.

**Comment by yoannchaudet** [comment]
See the usage information we documented in https://github.com/actions/deploy-pages#usage which are related to last week's release: https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/

**Pull request closed without merging**
