### PR TITLE
Add proxy options for Axios calls

### PR DESCRIPTION
**Pull request by jeremy-daley-kr**
For self-hosted runners where proxy is required, accepts an additional action input of `proxy` which is passed in as string to `https-proxy-agent`.

### CODE REVIEW

**Comment by daleyjem** [comment]
@JamesMGreene Had another thought, if not wanting to use a `proxy` input, the action could obey the http_proxy/https_proxy (HTTP_PROXY/HTTPS_PROXY) env vars.

**Comment by JamesMGreene** [comment]
@daleyjem / @jeremy-daley-kr: All good points. 👍🏻 

I'll look into this more today, as well as adding an issue to make sure we get those new API endpoints published to the REST docs now that they're more public (though still _technically_ "beta"... but a VERY heavily used beta 😊).

**Comment by JamesMGreene** [comment]
I'm thinking maybe it's time to switch from using `axios` to using [`@actions/http-client`](https://github.com/actions/toolkit/tree/main/packages/http-client), which is the layer underneath `@actions/github` that provides all of the built-in proxy support for Actions things. 🤔

**Comment by JamesMGreene** [comment]
Opened alternative PR:
- #124

Would be much obliged if you could assist with some real-world testing, @jeremy-daley-kr. 🙇🏻

**Comment by jeremy-daley-kr** [comment]
> * Use the `@actions/http-client` and `@actions/github` modules for proxy support #124

Nice! I'll see if I can get a test going from your branch.

**Pull request closed without merging**
